// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package splunk

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-splunk/sdk/go/splunk/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Resource: AuthenticationUsers
//
// Create and update user information or delete the user.
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-splunk/sdk/go/splunk"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := splunk.NewAuthenticationUsers(ctx, "user01", &splunk.AuthenticationUsersArgs{
//				Email:           pulumi.String("user01@example.com"),
//				ForceChangePass: pulumi.Bool(false),
//				Password:        pulumi.String("password01"),
//				Roles: pulumi.StringArray{
//					pulumi.String("terraform-user01-role"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
type AuthenticationUsers struct {
	pulumi.CustomResourceState

	// User default app. Overrides the default app inherited from the user roles.
	DefaultApp pulumi.StringOutput `pulumi:"defaultApp"`
	// User email address.
	Email pulumi.StringOutput `pulumi:"email"`
	// Force user to change password indication
	ForceChangePass pulumi.BoolPtrOutput `pulumi:"forceChangePass"`
	// Unique user login name.
	Name pulumi.StringOutput `pulumi:"name"`
	// User login password.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Full user name.
	Realname pulumi.StringOutput `pulumi:"realname"`
	// Restart background search job that has not completed when Splunk restarts indication.
	RestartBackgroundJobs pulumi.BoolOutput `pulumi:"restartBackgroundJobs"`
	// Role to assign to this user. At least one existing role is required.
	Roles pulumi.StringArrayOutput `pulumi:"roles"`
	// User timezone.
	Tz pulumi.StringOutput `pulumi:"tz"`
}

// NewAuthenticationUsers registers a new resource with the given unique name, arguments, and options.
func NewAuthenticationUsers(ctx *pulumi.Context,
	name string, args *AuthenticationUsersArgs, opts ...pulumi.ResourceOption) (*AuthenticationUsers, error) {
	if args == nil {
		args = &AuthenticationUsersArgs{}
	}

	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AuthenticationUsers
	err := ctx.RegisterResource("splunk:index/authenticationUsers:AuthenticationUsers", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthenticationUsers gets an existing AuthenticationUsers resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthenticationUsers(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthenticationUsersState, opts ...pulumi.ResourceOption) (*AuthenticationUsers, error) {
	var resource AuthenticationUsers
	err := ctx.ReadResource("splunk:index/authenticationUsers:AuthenticationUsers", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthenticationUsers resources.
type authenticationUsersState struct {
	// User default app. Overrides the default app inherited from the user roles.
	DefaultApp *string `pulumi:"defaultApp"`
	// User email address.
	Email *string `pulumi:"email"`
	// Force user to change password indication
	ForceChangePass *bool `pulumi:"forceChangePass"`
	// Unique user login name.
	Name *string `pulumi:"name"`
	// User login password.
	Password *string `pulumi:"password"`
	// Full user name.
	Realname *string `pulumi:"realname"`
	// Restart background search job that has not completed when Splunk restarts indication.
	RestartBackgroundJobs *bool `pulumi:"restartBackgroundJobs"`
	// Role to assign to this user. At least one existing role is required.
	Roles []string `pulumi:"roles"`
	// User timezone.
	Tz *string `pulumi:"tz"`
}

type AuthenticationUsersState struct {
	// User default app. Overrides the default app inherited from the user roles.
	DefaultApp pulumi.StringPtrInput
	// User email address.
	Email pulumi.StringPtrInput
	// Force user to change password indication
	ForceChangePass pulumi.BoolPtrInput
	// Unique user login name.
	Name pulumi.StringPtrInput
	// User login password.
	Password pulumi.StringPtrInput
	// Full user name.
	Realname pulumi.StringPtrInput
	// Restart background search job that has not completed when Splunk restarts indication.
	RestartBackgroundJobs pulumi.BoolPtrInput
	// Role to assign to this user. At least one existing role is required.
	Roles pulumi.StringArrayInput
	// User timezone.
	Tz pulumi.StringPtrInput
}

func (AuthenticationUsersState) ElementType() reflect.Type {
	return reflect.TypeOf((*authenticationUsersState)(nil)).Elem()
}

type authenticationUsersArgs struct {
	// User default app. Overrides the default app inherited from the user roles.
	DefaultApp *string `pulumi:"defaultApp"`
	// User email address.
	Email *string `pulumi:"email"`
	// Force user to change password indication
	ForceChangePass *bool `pulumi:"forceChangePass"`
	// Unique user login name.
	Name *string `pulumi:"name"`
	// User login password.
	Password *string `pulumi:"password"`
	// Full user name.
	Realname *string `pulumi:"realname"`
	// Restart background search job that has not completed when Splunk restarts indication.
	RestartBackgroundJobs *bool `pulumi:"restartBackgroundJobs"`
	// Role to assign to this user. At least one existing role is required.
	Roles []string `pulumi:"roles"`
	// User timezone.
	Tz *string `pulumi:"tz"`
}

// The set of arguments for constructing a AuthenticationUsers resource.
type AuthenticationUsersArgs struct {
	// User default app. Overrides the default app inherited from the user roles.
	DefaultApp pulumi.StringPtrInput
	// User email address.
	Email pulumi.StringPtrInput
	// Force user to change password indication
	ForceChangePass pulumi.BoolPtrInput
	// Unique user login name.
	Name pulumi.StringPtrInput
	// User login password.
	Password pulumi.StringPtrInput
	// Full user name.
	Realname pulumi.StringPtrInput
	// Restart background search job that has not completed when Splunk restarts indication.
	RestartBackgroundJobs pulumi.BoolPtrInput
	// Role to assign to this user. At least one existing role is required.
	Roles pulumi.StringArrayInput
	// User timezone.
	Tz pulumi.StringPtrInput
}

func (AuthenticationUsersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authenticationUsersArgs)(nil)).Elem()
}

type AuthenticationUsersInput interface {
	pulumi.Input

	ToAuthenticationUsersOutput() AuthenticationUsersOutput
	ToAuthenticationUsersOutputWithContext(ctx context.Context) AuthenticationUsersOutput
}

func (*AuthenticationUsers) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthenticationUsers)(nil)).Elem()
}

func (i *AuthenticationUsers) ToAuthenticationUsersOutput() AuthenticationUsersOutput {
	return i.ToAuthenticationUsersOutputWithContext(context.Background())
}

func (i *AuthenticationUsers) ToAuthenticationUsersOutputWithContext(ctx context.Context) AuthenticationUsersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationUsersOutput)
}

// AuthenticationUsersArrayInput is an input type that accepts AuthenticationUsersArray and AuthenticationUsersArrayOutput values.
// You can construct a concrete instance of `AuthenticationUsersArrayInput` via:
//
//	AuthenticationUsersArray{ AuthenticationUsersArgs{...} }
type AuthenticationUsersArrayInput interface {
	pulumi.Input

	ToAuthenticationUsersArrayOutput() AuthenticationUsersArrayOutput
	ToAuthenticationUsersArrayOutputWithContext(context.Context) AuthenticationUsersArrayOutput
}

type AuthenticationUsersArray []AuthenticationUsersInput

func (AuthenticationUsersArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthenticationUsers)(nil)).Elem()
}

func (i AuthenticationUsersArray) ToAuthenticationUsersArrayOutput() AuthenticationUsersArrayOutput {
	return i.ToAuthenticationUsersArrayOutputWithContext(context.Background())
}

func (i AuthenticationUsersArray) ToAuthenticationUsersArrayOutputWithContext(ctx context.Context) AuthenticationUsersArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationUsersArrayOutput)
}

// AuthenticationUsersMapInput is an input type that accepts AuthenticationUsersMap and AuthenticationUsersMapOutput values.
// You can construct a concrete instance of `AuthenticationUsersMapInput` via:
//
//	AuthenticationUsersMap{ "key": AuthenticationUsersArgs{...} }
type AuthenticationUsersMapInput interface {
	pulumi.Input

	ToAuthenticationUsersMapOutput() AuthenticationUsersMapOutput
	ToAuthenticationUsersMapOutputWithContext(context.Context) AuthenticationUsersMapOutput
}

type AuthenticationUsersMap map[string]AuthenticationUsersInput

func (AuthenticationUsersMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthenticationUsers)(nil)).Elem()
}

func (i AuthenticationUsersMap) ToAuthenticationUsersMapOutput() AuthenticationUsersMapOutput {
	return i.ToAuthenticationUsersMapOutputWithContext(context.Background())
}

func (i AuthenticationUsersMap) ToAuthenticationUsersMapOutputWithContext(ctx context.Context) AuthenticationUsersMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthenticationUsersMapOutput)
}

type AuthenticationUsersOutput struct{ *pulumi.OutputState }

func (AuthenticationUsersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuthenticationUsers)(nil)).Elem()
}

func (o AuthenticationUsersOutput) ToAuthenticationUsersOutput() AuthenticationUsersOutput {
	return o
}

func (o AuthenticationUsersOutput) ToAuthenticationUsersOutputWithContext(ctx context.Context) AuthenticationUsersOutput {
	return o
}

// User default app. Overrides the default app inherited from the user roles.
func (o AuthenticationUsersOutput) DefaultApp() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringOutput { return v.DefaultApp }).(pulumi.StringOutput)
}

// User email address.
func (o AuthenticationUsersOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// Force user to change password indication
func (o AuthenticationUsersOutput) ForceChangePass() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.BoolPtrOutput { return v.ForceChangePass }).(pulumi.BoolPtrOutput)
}

// Unique user login name.
func (o AuthenticationUsersOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// User login password.
func (o AuthenticationUsersOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// Full user name.
func (o AuthenticationUsersOutput) Realname() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringOutput { return v.Realname }).(pulumi.StringOutput)
}

// Restart background search job that has not completed when Splunk restarts indication.
func (o AuthenticationUsersOutput) RestartBackgroundJobs() pulumi.BoolOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.BoolOutput { return v.RestartBackgroundJobs }).(pulumi.BoolOutput)
}

// Role to assign to this user. At least one existing role is required.
func (o AuthenticationUsersOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringArrayOutput { return v.Roles }).(pulumi.StringArrayOutput)
}

// User timezone.
func (o AuthenticationUsersOutput) Tz() pulumi.StringOutput {
	return o.ApplyT(func(v *AuthenticationUsers) pulumi.StringOutput { return v.Tz }).(pulumi.StringOutput)
}

type AuthenticationUsersArrayOutput struct{ *pulumi.OutputState }

func (AuthenticationUsersArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AuthenticationUsers)(nil)).Elem()
}

func (o AuthenticationUsersArrayOutput) ToAuthenticationUsersArrayOutput() AuthenticationUsersArrayOutput {
	return o
}

func (o AuthenticationUsersArrayOutput) ToAuthenticationUsersArrayOutputWithContext(ctx context.Context) AuthenticationUsersArrayOutput {
	return o
}

func (o AuthenticationUsersArrayOutput) Index(i pulumi.IntInput) AuthenticationUsersOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AuthenticationUsers {
		return vs[0].([]*AuthenticationUsers)[vs[1].(int)]
	}).(AuthenticationUsersOutput)
}

type AuthenticationUsersMapOutput struct{ *pulumi.OutputState }

func (AuthenticationUsersMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AuthenticationUsers)(nil)).Elem()
}

func (o AuthenticationUsersMapOutput) ToAuthenticationUsersMapOutput() AuthenticationUsersMapOutput {
	return o
}

func (o AuthenticationUsersMapOutput) ToAuthenticationUsersMapOutputWithContext(ctx context.Context) AuthenticationUsersMapOutput {
	return o
}

func (o AuthenticationUsersMapOutput) MapIndex(k pulumi.StringInput) AuthenticationUsersOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AuthenticationUsers {
		return vs[0].(map[string]*AuthenticationUsers)[vs[1].(string)]
	}).(AuthenticationUsersOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthenticationUsersInput)(nil)).Elem(), &AuthenticationUsers{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthenticationUsersArrayInput)(nil)).Elem(), AuthenticationUsersArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AuthenticationUsersMapInput)(nil)).Elem(), AuthenticationUsersMap{})
	pulumi.RegisterOutputType(AuthenticationUsersOutput{})
	pulumi.RegisterOutputType(AuthenticationUsersArrayOutput{})
	pulumi.RegisterOutputType(AuthenticationUsersMapOutput{})
}
