# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SavedEventTypesArgs', 'SavedEventTypes']

@pulumi.input_type
class SavedEventTypesArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 search: pulumi.Input[_builtins.str],
                 acl: Optional[pulumi.Input['SavedEventTypesAclArgs']] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 priority: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a SavedEventTypes resource.

        :param pulumi.Input[_builtins.str] name: A name for the event type.
        :param pulumi.Input[_builtins.str] search: Event type search string.
        :param pulumi.Input['SavedEventTypesAclArgs'] acl: The app/user context that is the namespace for the resource
        :param pulumi.Input[_builtins.str] color: Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        :param pulumi.Input[_builtins.str] description: Human-readable description of this event type.
        :param pulumi.Input[_builtins.bool] disabled: If True, disables the event type.
        :param pulumi.Input[_builtins.int] priority: Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "search", search)
        if acl is not None:
            pulumi.set(__self__, "acl", acl)
        if color is not None:
            pulumi.set(__self__, "color", color)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        A name for the event type.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def search(self) -> pulumi.Input[_builtins.str]:
        """
        Event type search string.
        """
        return pulumi.get(self, "search")

    @search.setter
    def search(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "search", value)

    @_builtins.property
    @pulumi.getter
    def acl(self) -> Optional[pulumi.Input['SavedEventTypesAclArgs']]:
        """
        The app/user context that is the namespace for the resource
        """
        return pulumi.get(self, "acl")

    @acl.setter
    def acl(self, value: Optional[pulumi.Input['SavedEventTypesAclArgs']]):
        pulumi.set(self, "acl", value)

    @_builtins.property
    @pulumi.getter
    def color(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        """
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "color", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Human-readable description of this event type.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If True, disables the event type.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.input_type
class _SavedEventTypesState:
    def __init__(__self__, *,
                 acl: Optional[pulumi.Input['SavedEventTypesAclArgs']] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.int]] = None,
                 search: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering SavedEventTypes resources.

        :param pulumi.Input['SavedEventTypesAclArgs'] acl: The app/user context that is the namespace for the resource
        :param pulumi.Input[_builtins.str] color: Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        :param pulumi.Input[_builtins.str] description: Human-readable description of this event type.
        :param pulumi.Input[_builtins.bool] disabled: If True, disables the event type.
        :param pulumi.Input[_builtins.str] name: A name for the event type.
        :param pulumi.Input[_builtins.int] priority: Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        :param pulumi.Input[_builtins.str] search: Event type search string.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        if acl is not None:
            pulumi.set(__self__, "acl", acl)
        if color is not None:
            pulumi.set(__self__, "color", color)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if search is not None:
            pulumi.set(__self__, "search", search)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def acl(self) -> Optional[pulumi.Input['SavedEventTypesAclArgs']]:
        """
        The app/user context that is the namespace for the resource
        """
        return pulumi.get(self, "acl")

    @acl.setter
    def acl(self, value: Optional[pulumi.Input['SavedEventTypesAclArgs']]):
        pulumi.set(self, "acl", value)

    @_builtins.property
    @pulumi.getter
    def color(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        """
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "color", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Human-readable description of this event type.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If True, disables the event type.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A name for the event type.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter
    def search(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Event type search string.
        """
        return pulumi.get(self, "search")

    @search.setter
    def search(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "search", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("splunk:index/savedEventTypes:SavedEventTypes")
class SavedEventTypes(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acl: Optional[pulumi.Input[Union['SavedEventTypesAclArgs', 'SavedEventTypesAclArgsDict']]] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.int]] = None,
                 search: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        ## # Resource: SavedEventTypes

        Create and manage saved event types (knowledge objects).

        ## Example Usage

        ```python
        import pulumi
        import pulumi_splunk as splunk

        test = splunk.SavedEventTypes("test",
            name="test",
            description="Test New event description",
            disabled=False,
            priority=1,
            search="index=main",
            color="et_blue",
            tags=["tag"],
            acl={
                "owner": "admin",
                "sharing": "app",
                "app": "launcher",
            })
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['SavedEventTypesAclArgs', 'SavedEventTypesAclArgsDict']] acl: The app/user context that is the namespace for the resource
        :param pulumi.Input[_builtins.str] color: Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        :param pulumi.Input[_builtins.str] description: Human-readable description of this event type.
        :param pulumi.Input[_builtins.bool] disabled: If True, disables the event type.
        :param pulumi.Input[_builtins.str] name: A name for the event type.
        :param pulumi.Input[_builtins.int] priority: Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        :param pulumi.Input[_builtins.str] search: Event type search string.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SavedEventTypesArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Resource: SavedEventTypes

        Create and manage saved event types (knowledge objects).

        ## Example Usage

        ```python
        import pulumi
        import pulumi_splunk as splunk

        test = splunk.SavedEventTypes("test",
            name="test",
            description="Test New event description",
            disabled=False,
            priority=1,
            search="index=main",
            color="et_blue",
            tags=["tag"],
            acl={
                "owner": "admin",
                "sharing": "app",
                "app": "launcher",
            })
        ```


        :param str resource_name: The name of the resource.
        :param SavedEventTypesArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SavedEventTypesArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acl: Optional[pulumi.Input[Union['SavedEventTypesAclArgs', 'SavedEventTypesAclArgsDict']]] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.int]] = None,
                 search: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SavedEventTypesArgs.__new__(SavedEventTypesArgs)

            __props__.__dict__["acl"] = acl
            __props__.__dict__["color"] = color
            __props__.__dict__["description"] = description
            __props__.__dict__["disabled"] = disabled
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["priority"] = priority
            if search is None and not opts.urn:
                raise TypeError("Missing required property 'search'")
            __props__.__dict__["search"] = search
            __props__.__dict__["tags"] = tags
        super(SavedEventTypes, __self__).__init__(
            'splunk:index/savedEventTypes:SavedEventTypes',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            acl: Optional[pulumi.Input[Union['SavedEventTypesAclArgs', 'SavedEventTypesAclArgsDict']]] = None,
            color: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            disabled: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            priority: Optional[pulumi.Input[_builtins.int]] = None,
            search: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'SavedEventTypes':
        """
        Get an existing SavedEventTypes resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['SavedEventTypesAclArgs', 'SavedEventTypesAclArgsDict']] acl: The app/user context that is the namespace for the resource
        :param pulumi.Input[_builtins.str] color: Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        :param pulumi.Input[_builtins.str] description: Human-readable description of this event type.
        :param pulumi.Input[_builtins.bool] disabled: If True, disables the event type.
        :param pulumi.Input[_builtins.str] name: A name for the event type.
        :param pulumi.Input[_builtins.int] priority: Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        :param pulumi.Input[_builtins.str] search: Event type search string.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SavedEventTypesState.__new__(_SavedEventTypesState)

        __props__.__dict__["acl"] = acl
        __props__.__dict__["color"] = color
        __props__.__dict__["description"] = description
        __props__.__dict__["disabled"] = disabled
        __props__.__dict__["name"] = name
        __props__.__dict__["priority"] = priority
        __props__.__dict__["search"] = search
        __props__.__dict__["tags"] = tags
        return SavedEventTypes(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def acl(self) -> pulumi.Output['outputs.SavedEventTypesAcl']:
        """
        The app/user context that is the namespace for the resource
        """
        return pulumi.get(self, "acl")

    @_builtins.property
    @pulumi.getter
    def color(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Color for this event type. The supported colors are: none, et_blue, et_green, et_magenta, et_orange, et_purple, et_red, et_sky, et_teal, et_yellow.
        """
        return pulumi.get(self, "color")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Human-readable description of this event type.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If True, disables the event type.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        A name for the event type.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Specify an integer from 1 to 10 for the value used to determine the order in which the matching event types of an event are displayed. 1 is the highest priority.
        """
        return pulumi.get(self, "priority")

    @_builtins.property
    @pulumi.getter
    def search(self) -> pulumi.Output[_builtins.str]:
        """
        Event type search string.
        """
        return pulumi.get(self, "search")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        [Deprecated] Use tags.conf.spec file to assign tags to groups of events with related field values.
        """
        return pulumi.get(self, "tags")

