provider: splunk
docker: true
major-version: 1
env:
    SPLUNK_URL: localhost:8089
    SPLUNK_USERNAME: admin
    SPLUNK_PASSWORD: password
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
