// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("splunk");

/**
 * Authentication tokens, also known as JSON Web Tokens (JWT), are a method for authenticating Splunk platform users into
 * the Splunk platform
 */
export let authToken: string | undefined = __config.get("authToken");
/**
 * insecure skip verification flag
 */
export let insecureSkipVerify: boolean | undefined = __config.getObject<boolean>("insecureSkipVerify");
/**
 * Splunk instance password
 */
export let password: string | undefined = __config.get("password");
/**
 * Timeout when making calls to Splunk server. Defaults to 60 seconds
 */
export let timeout: number | undefined = __config.getObject<number>("timeout");
/**
 * Splunk instance URL
 */
export let url: string | undefined = __config.get("url");
/**
 * Splunk instance admin username
 */
export let username: string | undefined = __config.get("username");
