// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.splunk;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FederatedIndexesArgs extends com.pulumi.resources.ResourceArgs {

    public static final FederatedIndexesArgs Empty = new FederatedIndexesArgs();

    /**
     * Remote index, saved search, scheduled search (for `lastjob`), or data model name, without a type prefix. For example, use `main`, not `index:main`. Changes to either dataset field update the mapping in place.
     * 
     * Federated indexes require a standard-mode provider. Remote saved searches and data models must be readable by the provider&#39;s service account and shared globally or in the provider&#39;s app context. See [Splunk&#39;s remote dataset documentation](https://help.splunk.com/en/splunk-enterprise/search/search-manual/9.1/run-federated-searches-across-multiple-splunk-deployments/create-a-federated-index).
     * 
     */
    @Import(name="datasetName", required=true)
    private Output<String> datasetName;

    /**
     * @return Remote index, saved search, scheduled search (for `lastjob`), or data model name, without a type prefix. For example, use `main`, not `index:main`. Changes to either dataset field update the mapping in place.
     * 
     * Federated indexes require a standard-mode provider. Remote saved searches and data models must be readable by the provider&#39;s service account and shared globally or in the provider&#39;s app context. See [Splunk&#39;s remote dataset documentation](https://help.splunk.com/en/splunk-enterprise/search/search-manual/9.1/run-federated-searches-across-multiple-splunk-deployments/create-a-federated-index).
     * 
     */
    public Output<String> datasetName() {
        return this.datasetName;
    }

    /**
     * Remote dataset type. Accepts only `index`, `savedsearch`, `lastjob`, or `datamodel`. Defaults to `index`.
     * 
     */
    @Import(name="datasetType")
    private @Nullable Output<String> datasetType;

    /**
     * @return Remote dataset type. Accepts only `index`, `savedsearch`, `lastjob`, or `datamodel`. Defaults to `index`.
     * 
     */
    public Optional<Output<String>> datasetType() {
        return Optional.ofNullable(this.datasetType);
    }

    /**
     * Name of the federated provider containing the remote dataset.
     * 
     */
    @Import(name="federatedProvider", required=true)
    private Output<String> federatedProvider;

    /**
     * @return Name of the federated provider containing the remote dataset.
     * 
     */
    public Output<String> federatedProvider() {
        return this.federatedProvider;
    }

    /**
     * Local federated index name without the `federated:` prefix. Use lowercase letters, numbers, underscores, or hyphens, starting with a letter or number. The name must be at most 2048 characters and must not contain `kvstore`. Changing it creates a new index.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Local federated index name without the `federated:` prefix. Use lowercase letters, numbers, underscores, or hyphens, starting with a letter or number. The name must be at most 2048 characters and must not contain `kvstore`. Changing it creates a new index.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private FederatedIndexesArgs() {}

    private FederatedIndexesArgs(FederatedIndexesArgs $) {
        this.datasetName = $.datasetName;
        this.datasetType = $.datasetType;
        this.federatedProvider = $.federatedProvider;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FederatedIndexesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FederatedIndexesArgs $;

        public Builder() {
            $ = new FederatedIndexesArgs();
        }

        public Builder(FederatedIndexesArgs defaults) {
            $ = new FederatedIndexesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param datasetName Remote index, saved search, scheduled search (for `lastjob`), or data model name, without a type prefix. For example, use `main`, not `index:main`. Changes to either dataset field update the mapping in place.
         * 
         * Federated indexes require a standard-mode provider. Remote saved searches and data models must be readable by the provider&#39;s service account and shared globally or in the provider&#39;s app context. See [Splunk&#39;s remote dataset documentation](https://help.splunk.com/en/splunk-enterprise/search/search-manual/9.1/run-federated-searches-across-multiple-splunk-deployments/create-a-federated-index).
         * 
         * @return builder
         * 
         */
        public Builder datasetName(Output<String> datasetName) {
            $.datasetName = datasetName;
            return this;
        }

        /**
         * @param datasetName Remote index, saved search, scheduled search (for `lastjob`), or data model name, without a type prefix. For example, use `main`, not `index:main`. Changes to either dataset field update the mapping in place.
         * 
         * Federated indexes require a standard-mode provider. Remote saved searches and data models must be readable by the provider&#39;s service account and shared globally or in the provider&#39;s app context. See [Splunk&#39;s remote dataset documentation](https://help.splunk.com/en/splunk-enterprise/search/search-manual/9.1/run-federated-searches-across-multiple-splunk-deployments/create-a-federated-index).
         * 
         * @return builder
         * 
         */
        public Builder datasetName(String datasetName) {
            return datasetName(Output.of(datasetName));
        }

        /**
         * @param datasetType Remote dataset type. Accepts only `index`, `savedsearch`, `lastjob`, or `datamodel`. Defaults to `index`.
         * 
         * @return builder
         * 
         */
        public Builder datasetType(@Nullable Output<String> datasetType) {
            $.datasetType = datasetType;
            return this;
        }

        /**
         * @param datasetType Remote dataset type. Accepts only `index`, `savedsearch`, `lastjob`, or `datamodel`. Defaults to `index`.
         * 
         * @return builder
         * 
         */
        public Builder datasetType(String datasetType) {
            return datasetType(Output.of(datasetType));
        }

        /**
         * @param federatedProvider Name of the federated provider containing the remote dataset.
         * 
         * @return builder
         * 
         */
        public Builder federatedProvider(Output<String> federatedProvider) {
            $.federatedProvider = federatedProvider;
            return this;
        }

        /**
         * @param federatedProvider Name of the federated provider containing the remote dataset.
         * 
         * @return builder
         * 
         */
        public Builder federatedProvider(String federatedProvider) {
            return federatedProvider(Output.of(federatedProvider));
        }

        /**
         * @param name Local federated index name without the `federated:` prefix. Use lowercase letters, numbers, underscores, or hyphens, starting with a letter or number. The name must be at most 2048 characters and must not contain `kvstore`. Changing it creates a new index.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Local federated index name without the `federated:` prefix. Use lowercase letters, numbers, underscores, or hyphens, starting with a letter or number. The name must be at most 2048 characters and must not contain `kvstore`. Changing it creates a new index.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public FederatedIndexesArgs build() {
            if ($.datasetName == null) {
                throw new MissingRequiredPropertyException("FederatedIndexesArgs", "datasetName");
            }
            if ($.federatedProvider == null) {
                throw new MissingRequiredPropertyException("FederatedIndexesArgs", "federatedProvider");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("FederatedIndexesArgs", "name");
            }
            return $;
        }
    }

}
