// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.splunk;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.splunk.GenericAclArgs;
import com.pulumi.splunk.Utilities;
import com.pulumi.splunk.inputs.GenericAclState;
import com.pulumi.splunk.outputs.GenericAclAcl;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.splunk.GenericAcl;
 * import com.pulumi.splunk.GenericAclArgs;
 * import com.pulumi.splunk.inputs.GenericAclAclArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var myApp = new GenericAcl(&#34;myApp&#34;, GenericAclArgs.builder()        
 *             .acl(GenericAclAclArgs.builder()
 *                 .app(&#34;system&#34;)
 *                 .owner(&#34;nobody&#34;)
 *                 .reads(&#34;*&#34;)
 *                 .writes(                
 *                     &#34;admin&#34;,
 *                     &#34;power&#34;)
 *                 .build())
 *             .path(&#34;apps/local/my_app&#34;)
 *             .build());
 * 
 *         var myDashboard = new GenericAcl(&#34;myDashboard&#34;, GenericAclArgs.builder()        
 *             .acl(GenericAclAclArgs.builder()
 *                 .app(&#34;my_app&#34;)
 *                 .owner(&#34;joe_user&#34;)
 *                 .reads(&#34;team_joe&#34;)
 *                 .writes(&#34;team_joe&#34;)
 *                 .build())
 *             .path(&#34;data/ui/views/my_dashboard&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Generic ACL resources can be imported by specifying their owner, app, and path with a colon-delimited string as the ID
 * 
 * ```sh
 *  $ pulumi import splunk:index/genericAcl:GenericAcl splunk_generic_acl &lt;owner&gt;:&lt;app&gt;:&lt;path&gt;
 * ```
 * 
 */
@ResourceType(type="splunk:index/genericAcl:GenericAcl")
public class GenericAcl extends com.pulumi.resources.CustomResource {
    /**
     * The ACL to apply to the object, including app/owner to properly identify the object.
     * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
     * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
     * app and owner for objects that don&#39;t fit in the normal namespace.
     * 
     */
    @Export(name="acl", type=GenericAclAcl.class, parameters={})
    private Output<GenericAclAcl> acl;

    /**
     * @return The ACL to apply to the object, including app/owner to properly identify the object.
     * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
     * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
     * app and owner for objects that don&#39;t fit in the normal namespace.
     * 
     */
    public Output<GenericAclAcl> acl() {
        return this.acl;
    }
    /**
     * REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
     * 
     */
    @Export(name="path", type=String.class, parameters={})
    private Output<String> path;

    /**
     * @return REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
     * 
     */
    public Output<String> path() {
        return this.path;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GenericAcl(String name) {
        this(name, GenericAclArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GenericAcl(String name, GenericAclArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GenericAcl(String name, GenericAclArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("splunk:index/genericAcl:GenericAcl", name, args == null ? GenericAclArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private GenericAcl(String name, Output<String> id, @Nullable GenericAclState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("splunk:index/genericAcl:GenericAcl", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GenericAcl get(String name, Output<String> id, @Nullable GenericAclState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GenericAcl(name, id, state, options);
    }
}
