// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.splunk;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.splunk.inputs.GenericAclAclArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GenericAclArgs extends com.pulumi.resources.ResourceArgs {

    public static final GenericAclArgs Empty = new GenericAclArgs();

    /**
     * The ACL to apply to the object, including app/owner to properly identify the object.
     * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
     * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
     * app and owner for objects that don&#39;t fit in the normal namespace.
     * 
     */
    @Import(name="acl")
    private @Nullable Output<GenericAclAclArgs> acl;

    /**
     * @return The ACL to apply to the object, including app/owner to properly identify the object.
     * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
     * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
     * app and owner for objects that don&#39;t fit in the normal namespace.
     * 
     */
    public Optional<Output<GenericAclAclArgs>> acl() {
        return Optional.ofNullable(this.acl);
    }

    /**
     * REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
     * 
     */
    @Import(name="path", required=true)
    private Output<String> path;

    /**
     * @return REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
     * 
     */
    public Output<String> path() {
        return this.path;
    }

    private GenericAclArgs() {}

    private GenericAclArgs(GenericAclArgs $) {
        this.acl = $.acl;
        this.path = $.path;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GenericAclArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GenericAclArgs $;

        public Builder() {
            $ = new GenericAclArgs();
        }

        public Builder(GenericAclArgs defaults) {
            $ = new GenericAclArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param acl The ACL to apply to the object, including app/owner to properly identify the object.
         * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
         * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
         * app and owner for objects that don&#39;t fit in the normal namespace.
         * 
         * @return builder
         * 
         */
        public Builder acl(@Nullable Output<GenericAclAclArgs> acl) {
            $.acl = acl;
            return this;
        }

        /**
         * @param acl The ACL to apply to the object, including app/owner to properly identify the object.
         * Though technically optional, it should be explicitly set for this resource to really be valid. Some objects, such as
         * apps, require specific values for app and owner. Consult the REST API documentation regarding which values to use for
         * app and owner for objects that don&#39;t fit in the normal namespace.
         * 
         * @return builder
         * 
         */
        public Builder acl(GenericAclAclArgs acl) {
            return acl(Output.of(acl));
        }

        /**
         * @param path REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
         * 
         * @return builder
         * 
         */
        public Builder path(Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @param path REST API Endpoint path to the object, relative to servicesNS/&lt;owner&gt;/&lt;app&gt;
         * 
         * @return builder
         * 
         */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        public GenericAclArgs build() {
            if ($.path == null) {
                throw new MissingRequiredPropertyException("GenericAclArgs", "path");
            }
            return $;
        }
    }

}
