# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'auth_token',
    'insecure_skip_verify',
    'password',
    'timeout',
    'url',
    'username',
]

__config__ = pulumi.Config('splunk')

auth_token = __config__.get('authToken')
"""
Authentication tokens, also known as JSON Web Tokens (JWT), are a method for authenticating Splunk platform users into
the Splunk platform
"""

insecure_skip_verify = __config__.get('insecureSkipVerify')
"""
insecure skip verification flag
"""

password = __config__.get('password')
"""
Splunk instance password
"""

timeout = __config__.get('timeout')
"""
Timeout when making calls to Splunk server. Defaults to 60 seconds
"""

url = __config__.get('url')
"""
Splunk instance URL
"""

username = __config__.get('username')
"""
Splunk instance admin username
"""

